### ISSUE TITLE
Elp Blog

### ISSUE THREAD

**Issue by veryeasily** [YourBrainIsAInternet/yourbrainisainternet.github.io#2]
Write first blog entry which summarizes the first Bagend!

**Comment by coopaloopster** [comment]
# _skadoosh._

**Comment by kilianbreathnach** [comment]
you guys were doing this shit at 4? link to blog post pls?

**Comment by coopaloopster** [comment]
You mother fuckers made me coffee promising 5 episodes of ww2 and then passed out so I stayed up until 5 doing shit.
- Patrick
