### ISSUE TITLE
Figure out If this MoEffin thing Alreay Existizzle

### ISSUE THREAD

**Issue by veryeasily** [YourBrainIsAInternet/yourbrainisainternet.github.io#3]
I'm assigned this. I lied

**Comment by coopaloopster** [comment]
All sorts of shit like this exists.  But it's all just a bunch of dependency trees.  What we want are objects that the creator of the experiment will manipulate so as to make the path of logical inference of the most vital parts clear.  I deem this too custom to exist

# _Skadoosh_

**Comment by veryeasily** [comment]
could you provide some links?

**Comment by kilianbreathnach** [comment]
Here's a cool one I just found:

http://pycallgraph.slowchop.com/en/master/

and the one we already saw:

http://pythontutor.com/visualize.html#mode=edit

**Comment by veryeasily** [comment]
We may want to take a look at this also: http://www.google.com/patents/US20100199266

**Comment by coopaloopster** [comment]
this looks relevant but it also looks like complete shit haha
